tap 'caskroom/cask'
tap 'homebrew/boneyard'
# add support for Brewfile and brew bundle
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'nodenv/nodenv'
tap 'railwaycat/emacsmacport'
brew 'autoconf'
brew 'automate'
brew 'imagemagick'
brew 'glib'
brew 'nodenv'
brew 'emacs-mac'
